[server]
bind_address = "0.0.0.0:8889"
secret_key = "8Xui8SN4mI+7egV/9dlfYYLGQJeEx4+DwmSQLwDVXJg="

[meilisearch]
host = "http://192.168.2.19:7700"
apikey = "masterKey"

[log]
log_dir = "logs/"
log_cup = 1000
temp_size = "100MB"
zip_compress = true
rolling_type = "All"
level = "info"
debug = true
max_size = "1024MB"
file_name = "explorer.log"

